CryptoAnalysis/src/main/java/crypto/HeadlessCryptoScanner.java

This fix ensures that line numbers are returned so that they can be used in the IntelliJ plugin to apply markers in the editor. Currently, -1 one is returned when the line number is requested.

Added option to keep line numbers

---

CryptoAnalysis/src/main/java/crypto/analysis/CryptoScanner.java

For newer Java Versions like Java 11 the parameter less constructor of `LogManager.getLoccer()` might cause an `OperationNotSupportedException`. See [this Stackoverflow post](https://stackoverflow.com/questions/52953483/logmanager-getlogger-is-unable-to-determine-class-name-on-java-11) for details how the error looks like.
In my case I'm having troubles instantiating `new CryptoScanner(){ ... }` in the context of running in the JRE Environment of IntelliJ when the code was compiled with a JDK 11. Hence running an Analysis on IntelliJ IDEs crash.
Normal Applications that run outside the IntelliJ IDE context run fine with the current code however (even setting the executing JRE explicit to the internal IntellIiJ or Android Studio JRE).
As I'm not sure how this issue can be fixed without …

Fix possible OperationNotSupportedException

---

CryptoAnalysis/src/main/java/crypto/analysis/IAnalysisSeed.java
CryptoAnalysis/src/main/java/crypto/constraints/ConstraintSolver.java
CryptoAnalysis/src/test/java/tests/headless/StaticAnalysisDemoTest.java
CryptoAnalysisTargets/SSLMisuseExample/pom.xml
CryptoAnalysisTargets/SSLMisuseExample/src/main/java/crypto/SSLExample.java

- Added a boomerang query to find the points to information of the call site parameters. For each of the array parameters, its constants are found by traversing through the jimple method body.
- Added a headless test for SSLParameters.

Resolving #178

---

CryptoAnalysis/pom.xml
CryptoAnalysis/src/main/java/crypto/HeadlessCryptoScanner.java
CryptoAnalysis/src/main/java/crypto/analysis/CrySLRulesetSelector.java
CryptoAnalysis/src/main/java/crypto/cryslhandler/CrySLModelReader.java
CryptoAnalysis/src/main/java/crypto/providerdetection/ProviderDetection.java
CryptoAnalysis/src/test/java/tests/providerdetection/ProviderDetectionTestingFramework.java
CryptoAnalysis/src/test/java/tests/providerdetection/ProviderDetectionTests.java

This PR contains some refactoring and fixes regarding provider detection analysis. The changes in this PR are also used from the provider detection checkbox [PR](https://github.com/eclipse-cognicrypt/CogniCrypt/pull/360) in the CogniCrypt repository. The changes include:
- BouncyCastle-JCA ruleset added in POM file and is downloaded directly from Nexus server
- Refactored the provider detection analysis entry point in HeadessCryptoScanner
- Small fixes regarding NullPointerException error when fetching the CrySL rules
- Refactored ProviderDetection code and removed redundant methods and imports
- Methods from ProviderDetection class that were used for the provider detection JUnit tests, were moved into a newly created class called ProviderDetectionTestingFramework. This is done for having …

Provider detection analysis: Refactoring and small fixes

---

CryptoAnalysis/src/main/java/crypto/analysis/errors/AbstractError.java

Signed-off-by: AndreSonntag <Andre-Sonntag@gmx.de>
This PR contains the fix for Issue #218 
The AbstractError class required a further differentiation for JReturnStmt.

JReturnStmt cast fix

---

CryptoAnalysis/src/main/java/crypto/analysis/AnalysisSeedWithSpecification.java

This pull requests contains two minimal code changes to the analysis, which are required for the CogniCrypt_Fix prototype 
class AnalysisSeedWithSpecification.java 
- the field Map<Statement, SootMethod> allCallsOnObject = Maps.newLinkedHashMap(); is now a LinkedHashMap instead of HashMap
- add get method for the field allCallsOnObject

Required changes for the CogniCrypt_Fix prototype

---

CryptoAnalysis/pom.xml
CryptoAnalysis/src/main/java/crypto/constraints/ConstraintSolver.java
CryptoAnalysis/src/test/java/tests/headless/BouncyCastleHeadlessTest.java
CryptoAnalysis/src/test/java/tests/headless/BragaCryptoTest.java
CryptoAnalysis/src/test/java/tests/headless/CogniCryptGeneratedCodeTest.java
CryptoAnalysis/src/test/java/tests/headless/CryptoGuardTest.java
CryptoAnalysis/src/test/java/tests/headless/MessageDigestExampleTest.java
CryptoAnalysis/src/test/java/tests/headless/ReportedIssueTest.java
CryptoAnalysis/src/test/java/tests/headless/StaticAnalysisDemoTest.java
CryptoAnalysis/src/test/java/tests/pattern/BouncyCastlesUsagePatternTest.java
CryptoAnalysis/src/test/java/tests/pattern/CipherDigestIOStreamTest.java
CryptoAnalysis/src/test/java/tests/pattern/UsagePatternTest.java
CryptoAnalysis/src/test/java/tests/pattern/tink/TestDigitalSignature.java
Jenkinsfile

This PR fixes various test cases that were failing due to the upgrade of JCA in 1.5.0. The test cases were initially causing failures in the develop branch of CryptoAnalysis. The branch is still failing due to issue  #240

Fix various test cases in CryptoAnalysis

---

CryptoAnalysis/src/main/java/crypto/analysis/errors/AbstractError.java

This issue is mentioned previously:
https://github.com/CROSSINGTUD/CryptoAnalysis/pull/219#commitcomment-39481464
It is caused by the fact that JReturnVoidStmt is not an instance of
JAssignStmt, so the default condition cast attempt will fail in some cases.
Signed-off-by: Kristen Newbury <knewbury@ualberta.ca>

Fix abstractError bug when error location is at ReturnVoidStmt

---

CryptoAnalysis/pom.xml

Downgrade Tink dependency to get rid of errors in the tests.

Downgrade Tink dependency

---

CryptoAnalysis/pom.xml
CryptoAnalysis/src/main/java/crypto/reporting/CSVReporter.java
CryptoAnalysis/src/test/java/tests/headless/ReportFormatTest.java

This PR fixes the failing build of CryptoAnalysis in Jenkins CI. It introduces two fixes. Firstly, it downgrades the dependency of `maven-invoker-plugin` since the newer one introduces many API changes and as a result, many test cases are failing. Secondly, it fixes the NullPointerException error that was happening in one of the headless test cases.

Fix failing build of develop branch in Jenkins CI

---

CryptoAnalysis/src/main/java/crypto/HeadlessCryptoScanner.java
CryptoAnalysis/src/test/java/tests/headless/AbstractHeadlessTest.java

This PR fixes #353 after the issue was noticed by @Projucti. The redundant calls of the `getRules()` method are replaced with the usage of the `rules` field.
It is tested by running the CryptoAnalysis JAR in my machine and test its functionality manually. Furthermore, automatic tests complete successfully.

Fix redundant loading of rules in HeadlessCryptoScanner

---

CryptoAnalysis/src/main/java/crypto/reporting/SARIFConfig.java
CryptoAnalysis/src/main/java/crypto/reporting/SARIFReporter.java

SARIF report has thrown Nullpointer exceptions whenever CryptoAnalysis reported a HardcodedError or InstanceOfError.

Fix Nullpointer in SARIF

---

CryptoAnalysis/src/main/java/crypto/HeadlessCryptoScanner.java
CryptoAnalysis/src/main/java/crypto/analysis/CryptoScannerSettings.java
CryptoAnalysis/src/main/java/crypto/reporting/CSVReporter.java
CryptoAnalysis/src/main/java/crypto/reporting/CSVSummaryReporter.java
CryptoAnalysis/src/main/java/crypto/reporting/CommandLineReporter.java
CryptoAnalysis/src/main/java/crypto/reporting/ReportStatistics.java
CryptoAnalysis/src/main/java/crypto/reporting/Reporter.java
CryptoAnalysis/src/main/java/crypto/reporting/ReporterHelper.java
CryptoAnalysis/src/main/java/crypto/reporting/SARIFConfig.java
CryptoAnalysis/src/main/java/crypto/reporting/SARIFHelper.java
CryptoAnalysis/src/main/java/crypto/reporting/SARIFReporter.java
CryptoAnalysis/src/main/java/crypto/reporting/TXTReporter.java
CryptoAnalysis/src/test/java/tests/headless/AbstractHeadlessTest.java
CryptoAnalysis/src/test/java/tests/headless/ReportFormatTest.java
README.md

Refactor the reporter
-Update the reporters s.t. all reporters output the same information (see Issue #417 )
-Allow the usage of multiple report formats for a single analysis (see Issue #370 )
-Add flag to disable the analysis statistics in the reports (`--dstats`)
-Rework the CSV reporter: Previously, the CSV reporter only reports the number of errors, but no detailed information about the errors. Now the CSV reporter also reports all detailed information about the errors. The old CSV reporter (i.e. the "legacy" version) is still available by using the report format `CSV_SUMMARY` (see #370 )
-Update the README to document the changes and extend the information about the report formats (see #392 )
Closes #370, closes #392, closes #417

Reporter refactoring

---

CryptoAnalysis/src/main/java/crypto/analysis/errors/AbstractError.java
CryptoAnalysis/src/main/java/crypto/constraints/ConstraintSolver.java
CryptoAnalysis/src/test/java/tests/headless/BragaCryptoGoodusesTest.java
CryptoAnalysis/src/test/java/tests/headless/BragaCryptoMisusesTest.java
CryptoAnalysis/src/test/java/tests/pattern/IssuesTest.java

Before, the analysis returns a single required predicate as soon as it is found. Therefore, if the predicate is required in multiple statements only the first one was analyzed and reported. In this PR, the predicates are collected for the corresponding statements, s.t. each statement is analyzed independently.
Fix #421

Fix issue 421: Consider all method calls, when predicates are checked

---

CryptoAnalysis/src/main/java/crypto/analysis/AnalysisSeedWithSpecification.java
CryptoAnalysis/src/main/java/crypto/analysis/errors/AbstractError.java
CryptoAnalysis/src/main/java/crypto/constraints/ConstraintSolver.java
CryptoAnalysis/src/main/java/crypto/cryslhandler/CrySLModelReader.java
CryptoAnalysis/src/main/java/crypto/rules/CrySLRule.java
CryptoAnalysis/src/test/java/tests/headless/BragaCryptoGoodusesTest.java
CryptoAnalysis/src/test/java/tests/headless/BragaCryptoMisusesTest.java
CryptoAnalysis/src/test/java/tests/pattern/CipherTest.java
CryptoAnalysis/src/test/java/tests/pattern/ExtractValueTest.java
CryptoAnalysis/src/test/java/tests/pattern/IssuesTest.java
CryptoAnalysis/src/test/java/tests/pattern/PBETest.java
CryptoAnalysis/src/test/java/tests/pattern/SecretKeyTest.java

Before, conditional predicates (i.e. predicates with the "after" keyword) were ensured only for the state after the condition, and therefore negated implicitly in all following states. However, as defined in CrySL, the predicates should be ensured transitively in all following states as long as they are not negated. This PR extends the negates mechanism to ensure conditional predicates in all following states, which do not negate them.
Fix #418 
Fix #419

Update negates mechanism

---

CryptoAnalysis/src/main/java/crypto/rules/StateMachineGraph.java
CryptoAnalysis/src/main/java/crypto/typestate/CrySLMethodToSootMethod.java
CryptoAnalysis/src/main/java/crypto/typestate/FiniteStateMachineToTypestateChangeFunction.java
CryptoAnalysis/src/main/java/crypto/typestate/SootBasedStateMachineGraph.java
CryptoAnalysis/src/test/java/tests/pattern/CogniCryptTestGenTest.java

Currently, only the first initial transition in the state machine graph is considered in generating seeds. This leads to the problem that seeds are not found, if there initial calls are not labeled on this transition. In this PR, the state machine collects all initial transitions and considers all their labels when generating a seed. Also, the test cases from issue #296 are added that caused the problem.
Fix #296 
Fix #322

Change getInitialTransitions() to return all initial transitions

---

CryptoAnalysis/pom.xml
CryptoAnalysis/src/main/java/crypto/cryslhandler/CrySLModelReader.java
CryptoAnalysis/src/test/java/tests/headless/BouncyCastleHeadlessTest.java
CryptoAnalysis/src/test/java/tests/headless/BragaCryptoGoodusesTest.java
CryptoAnalysis/src/test/java/tests/headless/BragaCryptoMisusesTest.java
CryptoAnalysis/src/test/java/tests/pattern/BouncyCastleTest.java
CryptoAnalysisTargets/BCMacExamples/src/main/java/gwt_crypto/GMacTest.java
CryptoAnalysisTargets/BCSignerExamples/src/main/java/bop_bitcoin_client/ECKeyPair.java
CryptoAnalysisTargets/BCSymmetricCipherExamples/src/main/java/cbc_aes_example/CBCAESBouncyCastle.java
CryptoAnalysisTargets/BCSymmetricCipherExamples/src/main/java/gcm_aes_example/GCMAESBouncyCastle.java

-JCA 3.0.2: Rules for PrivateKey and PublicKey were added. This removes some false positives
-BouncyCastle 3.1.0: Some constructors are deprecated -> Update and extend the tests to conform the correct API usages

Update tests to match BC 3.1.0 and JCA 3.0.2

---

CryptoAnalysis/src/main/java/crypto/reporting/GitHubAnnotationReporter.java
README.md
action.yml

GitHub only displays 10 error annotations and silently drops the rest.
https://github.com/orgs/community/discussions/26680
https://github.com/orgs/community/discussions/68471
This PR adds a warning message when more than 10 violations are found.
Additionally, the `GitHubAnnotationReporter` now also outputs the normal command line report, so that the log contains all necessary information when not everything can be displayed using annotations.
The action setup also uses some grouping now to de-clutter the log.
Example run with more than 10 violations:
https://github.com/Timbals/CryptoAnalysis-demo/actions/runs/8086032882

Improvements for the GitHub Annotations limit

---

CryptoAnalysis/pom.xml

With the scopes `provided` and `test`, the `servlet` API and Tink are not on the classpath at runtime. Therefore, classes from those libraries cannot be parsed with CrySL rules, e.g. the `Cookie` class is not available. Removing the scopes adds the dependencies to the classpath at runtime

Remove scopes to have dependencies on classpath at runtime

---

CryptoAnalysis/src/main/java/crypto/constraints/PredicateConstraint.java
CryptoAnalysis/src/main/java/crypto/cryslhandler/CrySLModelReader.java

The second paramter of `instanceOf` and `neverTypeOf` is always a type (e.g. `javax.crypto.SecretKey`) and no name. However, internally the type was stored in the name field and not the type field of a `CrySLObject`. Changing type and name does not influence the analysis, but adds consistency. Detected by @svenfeld

Swap Type and Name of CrySLObject for instanceOf and neverTypeOf predicates

---

CryptoAnalysis/src/main/java/crypto/analysis/AnalysisSeedWithSpecification.java
CryptoAnalysis/src/main/java/crypto/analysis/errors/IncompleteOperationError.java
CryptoAnalysis/src/test/java/test/UsagePatternTestingFramework.java
CryptoAnalysis/src/test/java/test/assertions/Assertions.java
CryptoAnalysis/src/test/java/test/assertions/IncompleteOperationErrorCountAssertion.java
CryptoAnalysis/src/test/java/tests/custom/incompleteoperation/IncompleteOperationTest.java
CryptoAnalysis/src/test/java/tests/custom/incompleteoperation/Operations.java
CryptoAnalysis/src/test/java/tests/headless/BouncyCastleHeadlessTest.java
CryptoAnalysis/src/test/java/tests/headless/BragaCryptoGoodusesTest.java
CryptoAnalysis/src/test/java/tests/headless/BragaCryptoMisusesTest.java
CryptoAnalysis/src/test/java/tests/headless/StaticAnalysisDemoTest.java
CryptoAnalysis/src/test/resources/testrules/incompleteOperation/Operations.crysl

IncompleteOperationErrors are reported, if the a dataflow path does not end in an accepting state. However, if there are multiple dataflow paths, multiple IncompleteOperationErrors are reported, although some paths lead to an accepting state. For example, for
```
Cipher c = Cipher.getInstance([...]);
c.init([...]);
if (Math.random() > 0.5) {
c.doFinal([...]);
}
```
the analysis reports an error at the call to `init` with the info that a call to `doFinal` is missing, and it reports an error at the call to `doFinal` with the info that a call to `doFinal` is missing. The second error is not quite correct because `doFinal` is called on the corresponding dataflow path. Hence, this is a false positive.
This PR adds the logic for reporting the errors only on the correct positions (here at …

Fix incomplete operation errors

---

CryptoAnalysis/src/test/java/tests/headless/ReportedIssueTest.java
CryptoAnalysisTargets/ReportedIssues/pom.xml
CryptoAnalysisTargets/ReportedIssues/src/main/java/issue208/Issue208WithMultipleEntryPoints.java
CryptoAnalysisTargets/ReportedIssues/src/main/java/issue208/Issue208WithSingleEntryPoint.java
CryptoAnalysisTargets/ReportedIssues/src/main/java/issue69/Issue69.java

Add test from issue 208
Close #208

Add test case from #208

---

CryptoAnalysis/src/main/java/crypto/analysis/AlternativeReqPredicate.java
CryptoAnalysis/src/main/java/crypto/analysis/AnalysisSeedWithEnsuredPredicate.java
CryptoAnalysis/src/main/java/crypto/analysis/AnalysisSeedWithSpecification.java
CryptoAnalysis/src/main/java/crypto/analysis/CryptoScanner.java
CryptoAnalysis/src/main/java/crypto/analysis/EnsuredCrySLPredicate.java
CryptoAnalysis/src/main/java/crypto/analysis/IAnalysisSeed.java
CryptoAnalysis/src/main/java/crypto/analysis/PredicateHandler.java
CryptoAnalysis/src/main/java/crypto/analysis/RequiredCrySLPredicate.java
CryptoAnalysis/src/main/java/crypto/analysis/errors/RequiredPredicateError.java
CryptoAnalysis/src/main/java/crypto/constraints/ConstraintSolver.java
CryptoAnalysis/src/main/java/crypto/cryslhandler/StateMachineGraphBuilder.java
CryptoAnalysis/src/test/java/test/assertions/ConstraintErrorCountAssertion.java
CryptoAnalysis/src/test/java/test/assertions/HasEnsuredPredicateAssertion.java
CryptoAnalysis/src/test/java/test/assertions/NotHasEnsuredPredicateAssertion.java
CryptoAnalysis/src/test/java/tests/error/predicate/requiredpredicate/RequiredPredicatesTest.java
CryptoAnalysis/src/test/java/tests/error/predicate/requiredpredicateswiththis/RequiredPredicateWithThisTest.java
CryptoAnalysis/src/test/java/tests/error/predicate/requiredpredicateswiththis/Source.java
CryptoAnalysis/src/test/java/tests/error/predicate/requiredpredicateswiththis/TargetAlternative1.java
CryptoAnalysis/src/test/java/tests/error/predicate/requiredpredicateswiththis/TargetAlternative2.java
CryptoAnalysis/src/test/java/tests/error/predicate/requiredpredicateswiththis/TargetWithAlternatives.java
CryptoAnalysis/src/test/java/tests/headless/BragaCryptoGoodUsesTest.java
CryptoAnalysis/src/test/java/tests/headless/BragaCryptoMisusesTest.java
CryptoAnalysis/src/test/resources/testrules/requiredPredicateWithThis/Source.crysl
CryptoAnalysis/src/test/resources/testrules/requiredPredicateWithThis/TargetAlternative1.crysl
CryptoAnalysis/src/test/resources/testrules/requiredPredicateWithThis/TargetAlternative2.crysl
CryptoAnalysis/src/test/resources/testrules/requiredPredicateWithThis/TargetWithAlternatives.crysl
CryptoAnalysis/src/test/resources/testrules/requiredPredicateWithThis/UsingTarget.crysl
CryptoAnalysis/src/test/resources/testrules/requiredPredicates/Requires.crysl

Currently, if a predicate is ensured, it is just ensured for specific statements. Although this works with current rules, it is not precise if statements require the same predicate for multiple objects. For example, consider the method `superRandom(SecureRandom sr1, SecureRandom sr2)` and the `REQUIRES` section with `randomized[sr1]` and `randomized[sr2]`. In that case, CryptoAnalysis does not report an error if only one `randomized` predicate is ensured because as soon as one `randomized` is ensured, it holds for the complete statement, that is, there is no distinction between the parameters, and it assumes that the predicate counts for `sr1` and `sr2` despite only one object ensuring `randomized`.
This PR adds the parameter indices to the required predicates to be able to distinguish …

Update: More precise predicate comparing

---

CryptoAnalysis/src/main/java/crypto/analysis/CryptoScanner.java
CryptoAnalysis/src/main/java/crypto/constraints/ConstraintSolver.java
CryptoAnalysis/src/main/java/crypto/definition/ExtractParameterDefinition.java
CryptoAnalysis/src/main/java/crypto/listener/AnalysisPrinter.java
CryptoAnalysis/src/main/java/crypto/listener/AnalysisReporter.java
CryptoAnalysis/src/main/java/crypto/listener/AnalysisStatistics.java
CryptoAnalysis/src/main/java/crypto/listener/ErrorCollector.java
CryptoAnalysis/src/main/java/crypto/listener/IAnalysisListener.java
CryptoAnalysis/src/main/java/crypto/listener/IResultsListener.java
CryptoAnalysis/src/main/java/crypto/reporting/CSVReporter.java
CryptoAnalysis/src/main/java/crypto/reporting/CSVSummaryReporter.java
CryptoAnalysis/src/main/java/crypto/reporting/CommandLineReporter.java
CryptoAnalysis/src/main/java/crypto/reporting/GitHubAnnotationReporter.java
CryptoAnalysis/src/main/java/crypto/reporting/ReportGenerator.java
CryptoAnalysis/src/main/java/crypto/reporting/Reporter.java
CryptoAnalysis/src/main/java/crypto/reporting/SARIFReporter.java
CryptoAnalysis/src/main/java/crypto/reporting/TXTReporter.java
CryptoAnalysis/src/test/java/test/UsagePatternResultsListener.java
HeadlessAndroidScanner/src/main/java/de/fraunhofer/iem/android/HeadlessAndroidScanner.java
HeadlessJavaScanner/src/main/java/de/fraunhofer/iem/scanner/HeadlessJavaScanner.java

During the refactoring for the new Boomerang version, the analysis statistics in reports got lost due to the changed API of the call graph and statements. This adds the statistics, e.g. the analysis time, back to reports

Bring back analysis statistics to reports

---

.github/workflows/approve_dependabotifications.yml

trigger on pull_request_target to get context of base branch and only…on pom change i.e. allow only pom to change by dependabot
if that still has permissions issues - see https://stackoverflow.com/questions/70664840/automatic-merging-of-dependabot-generated-pull-request-with-codeowners-file-and

change execution context of the dependabot automerge workflow

---

CryptoAnalysis/src/main/java/crypto/analysis/AnalysisSeedWithSpecification.java
CryptoAnalysis/src/main/java/crypto/cryslhandler/StateMachineGraphBuilder.java
CryptoAnalysis/src/main/java/crypto/rules/CrySLConstraint.java
CryptoAnalysis/src/main/java/crypto/rules/CrySLExceptionConstraint.java
CryptoAnalysis/src/main/java/crypto/rules/CrySLLiteral.java
CryptoAnalysis/src/main/java/crypto/rules/ISLConstraint.java
CryptoAnalysis/src/test/java/test/UsagePatternTestingFramework.java
CryptoAnalysis/src/test/java/test/assertions/InAcceptingStateAssertion.java
CryptoAnalysis/src/test/java/test/assertions/NotInAcceptingStateAssertion.java
CryptoAnalysis/src/test/java/tests/jca/CogniCryptTestGenTest.java
CryptoAnalysis/src/test/java/tests/jca/PBETest.java
HeadlessJavaScanner/src/test/java/scanner/targets/BouncyCastleHeadlessTest.java
pom.xml

For expressions in the `ORDER` section of the form `(Op1?, Op2)*`, the state machine is missing an edge. Currently, there are tree states `0`, `1` and `2` with the edges `0 --Op1--> 1`, `1 --Op2--> 2`, `0 --Op2--> 2` and `2 --Op1--> 1`. This forces to use `Op1` after using `Op2` and being in state `2`. However, since `Op1` is optional, there is a missing edge `2 --Op2--> 2` that models using `Op2` mulitple times. This edge is added with this PR.
Close #295

Fix edges in state machine when dealing with optionals
