- CryptoAnalysis/src/main/java/crypto/typestate/FiniteStateMachineToTypestateChangeFunction.java
Changed the collection of RefType to a single variable. Added a check for different types in the initial transition label.
Results for all the tests are the same as the results for the run prior to the changes.
> Fix for issue #47

- CryptoAnalysis/src/main/java/crypto/analysis/errors/RequiredPredicateError.java
Added white spaces to generated predicate
> Updated RequiredPredicateError.java

- CryptoAnalysis/src/main/java/crypto/analysis/errors/TypestateError.java
Removing angle braces in TypestateError
> Removing angle braces in TypestateError

- CryptoAnalysis/src/main/java/crypto/analysis/errors/AbstractError.java
- CryptoAnalysis/src/main/java/crypto/analysis/errors/ConstraintError.java
- CryptoAnalysis/src/main/java/crypto/analysis/errors/ForbiddenMethodError.java
- CryptoAnalysis/src/main/java/crypto/analysis/errors/ImpreciseValueExtractionError.java
- CryptoAnalysis/src/main/java/crypto/analysis/errors/IncompleteOperationError.java
- CryptoAnalysis/src/main/java/crypto/analysis/errors/RequiredPredicateError.java
- CryptoAnalysis/src/main/java/crypto/analysis/errors/TypestateError.java
- CryptoAnalysis/src/main/java/crypto/constraints/ConstraintSolver.java
Reverts CROSSINGTUD/CryptoAnalysis#146
> Revert "Error hash code method"

- CryptoAnalysis/src/main/java/crypto/analysis/AnalysisSeedWithSpecification.java
- CryptoAnalysis/src/main/java/crypto/rules/StateMachineGraph.java
- CryptoAnalysis/src/main/java/crypto/rules/StateNode.java
> Getting changes from develop.

- CryptoAnalysis-Android/src/main/java/de/fraunhofer/iem/crypto/CogniCryptAndroidAnalysis.java
Expose analysis relevant metadata to eliminate the need of a wrapper class that hold the analysis and other data.
> Exposing metadata

- CryptoAnalysis/pom.xml
- CryptoAnalysis/src/main/java/crypto/analysis/CrySLRulesetSelector.java
- CryptoAnalysis/src/main/java/crypto/cryptslhandler/CrySLModelReader.java
- CryptoAnalysis/src/main/java/crypto/cryptslhandler/CryslReaderUtils.java
- Related to pull request #167's performance issue.
- Once rules in source format are read, create bin rule files and use in further analysis
> Pull request for improving performance while reading rules in source format. 

- README.md
- Usage :
In general the tool takes the rules in their  source code format (cryptsl). Optionally the analysis can be started with binary rules (cryptslbin).
- Changing the CrySL Rules:
You can use any text editor to modify the rules.
> Update README.md (relaed to pull request #167)

- CryptoAnalysis/src/main/java/crypto/analysis/CrySLRulesetSelector.java
- CryptoAnalysis/src/main/java/crypto/cryptslhandler/CrySLModelReader.java
- Requires related changes in cryptsl repository and updated cipher rule (See cryptsl pull request#22  & Crypto-API-Rules pull request#47 )
- Fixed unnecessary function (readFromSourceFile) call  in CrySLRulesetSelector class
> Changes related to Cryptsl issue 16 (shorthands for part(...) predicates.) 

- CryptoAnalysis/src/main/java/crypto/providerdetection/ProviderDetection.java
> Issue 179: Provider detection works with rules in SOURCE format

- CryptoAnalysis/pom.xml
- CryptoAnalysis/src/test/java/tests/pattern/CookiesTest.java
Added test case for Cookie.cryptsl
> Added Test case for Cookie.cryptsl

- CryptoAnalysis/src/main/java/crypto/analysis/CrySLResultsReporter.java
- CryptoAnalysis/src/main/java/crypto/analysis/CryptoScanner.java
- CryptoAnalysis/src/main/java/crypto/analysis/ICrySLResultsListener.java
- CryptoAnalysis/src/main/java/crypto/reporting/CSVReporter.java
- CryptoAnalysis/src/main/java/crypto/reporting/CollectErrorListener.java
- CryptoAnalysis/src/main/java/crypto/reporting/ErrorMarkerListener.java
- CryptoAnalysis/src/test/java/test/UsagePatternTestingFramework.java
- CryptoAnalysis/src/test/java/tests/headless/AbstractHeadlessTest.java
Added issue 196(Progress bar) code changes
> Added issue 196(Progress bar) code changes

- CryptoAnalysis/src/main/java/crypto/HeadlessCryptoScanner.java
- CryptoAnalysis/src/main/java/crypto/HeadlessCryptoScannerOptions.java
- CryptoAnalysis/src/main/java/crypto/analysis/CrySLRulesetSelector.java
- CryptoAnalysis/src/main/java/crypto/cryptslhandler/CryslReaderUtils.java
- CryptoAnalysis/src/main/java/crypto/providerdetection/ProviderDetection.java
- CryptoAnalysis/src/main/java/crypto/rules/CryptSLRuleReader.java
Removing the support for processing 'cryptslbin' files.
> Removing binary rule option

- CryptoAnalysis/src/main/java/crypto/analysis/AnalysisSeedWithSpecification.java
- CryptoAnalysis/src/main/java/crypto/cryptslhandler/CrySLModelReader.java
The pull requests need to be accepted in the following order:
1.	CrySL
2.	CryptoAnalysis
3.	CogniCrypt
This pull request contains:
- adjustments of the CrySLModelReader class for the new CrySL grammar extension (constraints for the ENSURES section)
- checks of the new introduced ENSURES constraints 
Fixes # (issue)
https://github.com/CROSSINGTUD/CryptoAnalysis/issues/80
**Test Configuration**:
* Eclipse Version: Oxygen.1a Release (4.7.1a)
* Java Version: 1.8.0_111
* OS: Windows 10
* Apache Maven 3.5.2
> Ensures predicate

- CryptoAnalysis-Android/pom.xml
- CryptoAnalysis/pom.xml
- CryptoAnalysisTargets/OracleExample/src/Crypto/PWHasher.java
- CryptoAnalysisTargets/OracleExample/src/main/java/Crypto/PWHasher.java
- CryptoAnalysisTargets/UserAuthenticator/src/main/java/Crypto/PWHasher.java
> update versions to 2.7.3-SNAPSHOT

- CryptoAnalysis/pom.xml
- CryptoAnalysis/src/test/java/tests/headless/StaticAnalysisDemoTest.java
- CryptoAnalysis/src/test/java/tests/pattern/CipherTest.java
This PR adds some small fixes so that the build of CryptoAnalysis in the Jenkins server is successful.
> Add small fixes to the build of CryptoAnalysis in Jenkins server

- CryptoAnalysis/pom.xml
- CryptoAnalysis/src/main/java/crypto/reporting/CSVReporter.java
- CryptoAnalysis/src/main/java/crypto/reporting/ReporterHelper.java
- CryptoAnalysis/src/main/java/crypto/reporting/SARIFConfig.java
- CryptoAnalysis/src/main/java/crypto/reporting/SARIFHelper.java
- CryptoAnalysis/src/main/java/crypto/reporting/SARIFReporter.java
fixes #307 
This pull requests fixes the reporting format of the sarifoutput. 
Also fixes the output for txt and csv.
> Fixed the output of reporting classes

- CryptoAnalysis/src/main/java/crypto/cryslhandler/StateMachineGraphBuilder.java
Signed-off-by: Anemone Kampkötter <anemone@kampkoetter.de>
> Documentation for Statemachine

- .github/workflows/deploy.yml
- .gitignore
- CryptoAnalysis-Android/pom.xml
- CryptoAnalysis/pom.xml
- pom.xml
Change URL's to Sonatype servers, update poms to enable deployment and add deployment workflow
> CryptoAnalysis 2.8.0 Deployment

- CryptoAnalysis-Android/src/main/java/de/fraunhofer/iem/crypto/CogniCryptAndroidAnalysis.java
- README.md
- pom.xml
> Add requested changes from issue 171 and 281

- .github/workflows/deploy.yml
- CryptoAnalysis/pom.xml
Update missing meta information for cryptoanalysis submodule and change actions to only deploy submodule
> Deploy ca submodule 2.7.2

- CryptoAnalysis/src/test/java/tests/headless/ReportedIssueTest.java
- CryptoAnalysisTargets/ReportedIssues/pom.xml
- CryptoAnalysisTargets/ReportedIssues/src/main/java/issue69/Issue69.java
Add test case from Issue 69
Close #69
> Add test case from #69

- CryptoAnalysis/src/main/java/crypto/analysis/AnalysisSeedWithSpecification.java
- CryptoAnalysis/src/main/java/crypto/reporting/ReportGenerator.java
- CryptoAnalysis/src/main/java/crypto/typestate/MatcherTransitionCollection.java
- CryptoAnalysis/src/test/java/tests/headless/ReportedIssueTest.java
- CryptoAnalysis/src/test/java/tests/jca/BouncyCastleTest.java
- CryptoAnalysisTargets/ReportedIssues/src/main/java/issue227/AbstractWrappedHasher.java
- CryptoAnalysisTargets/ReportedIssues/src/main/java/issue227/Hasher.java
- CryptoAnalysisTargets/ReportedIssues/src/main/java/issue227/Main.java
- CryptoAnalysisTargets/ReportedIssues/src/main/java/issue227/WrappedHasher.java
The program from #227 does not report a TypestateError anymore.
Close #227
> Add test case from #227

- CryptoAnalysis/src/main/java/crypto/analysis/AnalysisSeedWithSpecification.java
- CryptoAnalysis/src/main/java/crypto/reporting/ReportGenerator.java
- CryptoAnalysis/src/main/java/crypto/typestate/MatcherTransitionCollection.java
- CryptoAnalysis/src/test/java/tests/headless/ReportedIssueTest.java
- CryptoAnalysis/src/test/java/tests/jca/BouncyCastleTest.java
- CryptoAnalysisTargets/KotlinExamples/Issue271/pom.xml
- CryptoAnalysisTargets/KotlinExamples/Issue271/src/main/java/example/Issue271Kotlin.kt
- CryptoAnalysisTargets/KotlinExamples/issue271/src/main/java/example/Issue271Java.java
- CryptoAnalysisTargets/ReportedIssues/src/main/java/issue227/AbstractWrappedHasher.java
- CryptoAnalysisTargets/ReportedIssues/src/main/java/issue227/Hasher.java
- CryptoAnalysisTargets/ReportedIssues/src/main/java/issue227/Main.java
- CryptoAnalysisTargets/ReportedIssues/src/main/java/issue227/WrappedHasher.java
Add the test cases from #271. Using Kotlin 2.0.0, no changes were needed and the false positive is not reported anymore.
Close #271
> Add test case from #271

- .github/workflows/deploy_and_release.yml
Add examples.jar and JCA zip to the release upload.
> Fix and add additional files to release

- .github/workflows/dependency_analysis.yml
- CryptoAnalysis/pom.xml
- HeadlessAndroidScanner/pom.xml
- HeadlessJavaScanner/pom.xml
- pom.xml
> 819 add checks for maven dependencies

- HeadlessAndroidScanner/src/main/java/de/fraunhofer/iem/android/AndroidSettings.java
- HeadlessAndroidScanner/src/main/java/de/fraunhofer/iem/android/FlowDroidSetup.java
- HeadlessAndroidScanner/src/main/java/de/fraunhofer/iem/android/HeadlessAndroidScanner.java
- HeadlessAndroidScanner/src/test/java/settings/CommandLineTest.java
- HeadlessAndroidScanner/src/test/java/settings/ProgramTest.java
- README.md
Select a call graph with the `--cg` argument when running the Android scanner
> Add call graph selection to Android scanner
